# Site Build Settings

# jekyll-paginate configuration
paginate:            5
paginate_path:       "/galleries/page:num/"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:title
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "Flightless Photos"
description:	       "Boston and New England Photography Services"
author:              "© Flightless Photos LLC, 2025. All Rights Reserved."

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml
